package com.hive.delivery.domain;

public final class Enums {
    private Enums() {}
    public enum ProjectStatus { CREATED, RUNNING, WAITING, COMPLETED, FAILED, PAUSED }
    public enum NodeType { STAGE, TASK, GATE }
    public enum NodeStatus { PENDING, READY, DISPATCHING, RUNNING, WAITING_EXTERNAL, WAITING_HUMAN, COMPLETED, FAILED, BLOCKED, CANCELLED, SUPERSEDED }
    public enum ExecutorType { AGENT, CODE, HUMAN, EXTERNAL_SYSTEM, NONE }
    public enum EdgeType { DEPENDS_ON }
    public enum RunStatus { CREATED, RUNNING, WAITING_EXTERNAL, COMPLETED, FAILED, ABORTED }
    public enum EventType { PROJECT_CREATED, PROJECT_STARTED, STAGE_EXPANDED, NODE_READY, NODE_STARTED, NODE_WAITING, NODE_COMPLETED, NODE_FAILED, HUMAN_APPROVED, HUMAN_REJECTED, STAGE_COMPLETED, PROJECT_COMPLETED, CHANGE_REQUESTED, GRAPH_PATCHED }
}
